import { DEPENDENCIAS_MODULOS_CONFIGURACION, METODOS_PAGO_CONFIGURACION, MODULOS_CONFIGURACION, PAISES_FISCALES_SOPORTADOS, PERFIL_FISCAL_COLOMBIA, ROLES_TURNO_CONFIGURACION } from "./catalogos";
import { validarBranding, type ErrorBranding } from "./branding";
import type { ConfiguracionEmpresa } from "./contrato";
import { esEmailCanonico, esTelefonoCanonico, esTextoCanonico } from "./normalizacion";

export interface ErrorConfiguracion { ruta: string; codigo: string; mensaje: string }
export interface ResultadoValidacionConfiguracion<T = ConfiguracionEmpresa> { valida: boolean; errores: readonly ErrorConfiguracion[]; valor?: T }
export interface ContextoValidacionConfiguracion { empresaId?: string; paisFiscalEmpresa?: string; modulosPermitidos?: readonly string[]; metodosPagoPermitidos?: readonly string[] }

const SECCIONES = ["identidadFiscal", "localizacion", "impuestos", "branding", "ticket", "impresion", "pos", "caja", "modulos", "kds", "autenticacionOperativa", "preferencias"] as const;
const RAIZ = ["empresaId", "schemaVersion", "revision", ...SECCIONES, "creadaEn", "actualizadaEn", "ultimaMutacion"];
const CAMPOS: Record<string, readonly string[]> = {
  identidadFiscal: ["nombreComercial", "razonSocial", "tipoPersona", "tipoDocumento", "numeroDocumento", "digitoVerificacion", "regimenTributario", "responsabilidadesFiscales", "actividadEconomicaPrincipal", "contacto"], localizacion: ["paisFiscal", "moneda", "idioma", "zonaHoraria", "direccion"], impuestos: ["preciosIncluyenImpuestos", "impuestoTipoPredeterminado", "politicaRedondeo"], branding: ["modelVersion", "nombreVisible", "assets", "modoVisual", "paletas"], ticket: ["logoDocumentoUrl", "mensajePie", "mostrarLogoDocumento", "mostrarRazonSocial", "mostrarDireccion", "mostrarTelefono", "mostrarDesgloseImpuestos"], impresion: ["formatoPapel", "copiasVenta", "copiasCierre", "autoImprimirVenta", "autoAbrirCajon"], pos: ["metodosPagoHabilitados", "metodoPagoPredeterminado", "permitirPagoMixto", "permitirVentaSinExistencias", "requerirClienteEnCuentaCobro"], caja: ["baseAperturaSugerida", "umbralAlertaFaltante", "rolesConTurnoObligatorio", "permitirRelevo"], modulos: ["habilitados"], kds: ["ordenComandas", "minutosAlerta", "minutosCritico", "agruparPorPedido"], autenticacionOperativa: ["metodoPrincipal", "longitudPin", "maxFallosConsecutivos", "bloqueoMinutos", "exigirCambioCredencialTemporal"], preferencias: ["formatoFecha", "formatoHora", "primerDiaSemana", "mostrarCentavos"], contacto: ["email", "telefono"], direccion: ["linea1", "linea2", "departamentoCodigo", "departamentoNombre", "municipioCodigo", "municipioNombre", "codigoPostal"], ultimaMutacion: ["actorTipo", "actorId", "origen", "commandId", "correlationId", "motivo"], paletas: ["light", "dark"] };
const enumEn = (v: unknown, valores: readonly string[]) => typeof v === "string" && valores.includes(v);
const entero = (v: unknown, min: number, max = Number.MAX_SAFE_INTEGER) => Number.isInteger(v) && (v as number) >= min && (v as number) <= max;
const objeto = (v: unknown): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v);
function claves(v: unknown, ruta: string, esperadas: readonly string[], errores: ErrorConfiguracion[]): v is Record<string, unknown> { if (!objeto(v)) { errores.push({ ruta, codigo: "CONFIG_INVALID", mensaje: "Se requiere objeto." }); return false; } for (const k of Object.keys(v)) if (!esperadas.includes(k)) errores.push({ ruta: `${ruta}.${k}`, codigo: "CONFIG_FIELD_FORBIDDEN", mensaje: "Campo no permitido." }); return true; }
function obligatorio(v: unknown, ruta: string, errores: ErrorConfiguracion[], max = 240) { if (!esTextoCanonico(v, 1, max)) errores.push({ ruta, codigo: "CONFIG_REQUIRED", mensaje: "Texto obligatorio inválido." }); }
function opcional(v: unknown, ruta: string, errores: ErrorConfiguracion[], max = 240) { if (v !== undefined && !esTextoCanonico(v, 1, max)) errores.push({ ruta, codigo: "CONFIG_INVALID", mensaje: "Texto opcional inválido." }); }
function lista(v: unknown, ruta: string, permitidos: readonly string[], errores: ErrorConfiguracion[]) { if (!Array.isArray(v) || v.some((x) => !enumEn(x, permitidos)) || new Set(v).size !== v.length) errores.push({ ruta, codigo: "CONFIG_INVALID", mensaje: "Lista inválida o duplicada." }); }
function nitValido(numero: string, dv: string): boolean { if (!/^\d{6,15}$/.test(numero) || !/^\d$/.test(dv)) return false; const pesos = [71, 67, 59, 53, 47, 43, 41, 37, 29, 23, 19, 17, 13, 7, 3]; let suma = 0; for (let i = 0; i < numero.length; i += 1) suma += Number(numero[numero.length - 1 - i]) * pesos[pesos.length - 1 - i]; const resto = suma % 11; return Number(dv) === (resto > 1 ? 11 - resto : resto); }

export function validarConfiguracionEmpresa(documento: unknown, contexto: ContextoValidacionConfiguracion = {}): ResultadoValidacionConfiguracion {
  const errores: ErrorConfiguracion[] = [];
  if (!claves(documento, "", RAIZ, errores)) return { valida: false, errores };
  const c = documento as unknown as ConfiguracionEmpresa;
  for (const seccion of SECCIONES) claves(c[seccion], seccion, CAMPOS[seccion], errores);
  if (claves(c.identidadFiscal?.contacto, "identidadFiscal.contacto", CAMPOS.contacto, errores)) { if (c.identidadFiscal.contacto.email !== undefined && !esEmailCanonico(c.identidadFiscal.contacto.email)) errores.push({ ruta: "identidadFiscal.contacto.email", codigo: "CONFIG_INVALID", mensaje: "Email inválido." }); if (c.identidadFiscal.contacto.telefono !== undefined && !esTelefonoCanonico(c.identidadFiscal.contacto.telefono)) errores.push({ ruta: "identidadFiscal.contacto.telefono", codigo: "CONFIG_INVALID", mensaje: "Teléfono inválido." }); }
  claves(c.localizacion?.direccion, "localizacion.direccion", CAMPOS.direccion, errores); claves(c.ultimaMutacion, "ultimaMutacion", CAMPOS.ultimaMutacion, errores); if (objeto(c.branding?.paletas)) claves(c.branding.paletas, "branding.paletas", CAMPOS.paletas, errores);
  if (SECCIONES.some((seccion) => !objeto(c[seccion])) || !objeto(c.identidadFiscal?.contacto) || !objeto(c.localizacion?.direccion) || !objeto(c.ultimaMutacion)) return { valida: false, errores };
  obligatorio(c.empresaId, "empresaId", errores); if (!entero(c.schemaVersion, 1, 1)) errores.push({ ruta: "schemaVersion", codigo: "CONFIG_SCHEMA_UNSUPPORTED", mensaje: "Schema no soportado." }); if (!entero(c.revision, 1)) errores.push({ ruta: "revision", codigo: "CONFIG_INVALID", mensaje: "Revisión inválida." }); if (c.creadaEn == null || c.actualizadaEn == null) errores.push({ ruta: "timestamps", codigo: "CONFIG_REQUIRED", mensaje: "Metadatos temporales obligatorios." });
  obligatorio(c.identidadFiscal?.nombreComercial, "identidadFiscal.nombreComercial", errores, 120); ["razonSocial", "tipoDocumento", "numeroDocumento", "digitoVerificacion", "actividadEconomicaPrincipal"].forEach((k) => opcional((c.identidadFiscal as unknown as Record<string, unknown>)?.[k], `identidadFiscal.${k}`, errores)); if (c.identidadFiscal?.tipoPersona !== undefined && !enumEn(c.identidadFiscal.tipoPersona, ["NATURAL", "JURIDICA"])) errores.push({ ruta: "identidadFiscal.tipoPersona", codigo: "CONFIG_INVALID", mensaje: "Tipo de persona inválido." });
  if (c.identidadFiscal?.responsabilidadesFiscales !== undefined && (!Array.isArray(c.identidadFiscal.responsabilidadesFiscales) || new Set(c.identidadFiscal.responsabilidadesFiscales).size !== c.identidadFiscal.responsabilidadesFiscales.length || c.identidadFiscal.responsabilidadesFiscales.some((x) => !esTextoCanonico(x)))) errores.push({ ruta: "identidadFiscal.responsabilidadesFiscales", codigo: "CONFIG_INVALID", mensaje: "Responsabilidades inválidas." });
  obligatorio(c.localizacion?.paisFiscal, "localizacion.paisFiscal", errores, 2); obligatorio(c.localizacion?.moneda, "localizacion.moneda", errores, 3); obligatorio(c.localizacion?.idioma, "localizacion.idioma", errores, 16); obligatorio(c.localizacion?.zonaHoraria, "localizacion.zonaHoraria", errores, 64); if (contexto.empresaId && c.empresaId !== contexto.empresaId) errores.push({ ruta: "empresaId", codigo: "CONFIG_EMPRESA_MISMATCH", mensaje: "Empresa inconsistente." }); if (contexto.paisFiscalEmpresa && c.localizacion.paisFiscal !== contexto.paisFiscalEmpresa) errores.push({ ruta: "localizacion.paisFiscal", codigo: "CONFIG_COUNTRY_MISMATCH", mensaje: "País fiscal inconsistente." });
  if (c.localizacion.paisFiscal === "CO") { if (c.localizacion.moneda !== PERFIL_FISCAL_COLOMBIA.moneda || c.localizacion.idioma !== PERFIL_FISCAL_COLOMBIA.idioma || c.localizacion.zonaHoraria !== PERFIL_FISCAL_COLOMBIA.zonaHoraria) errores.push({ ruta: "localizacion", codigo: "CONFIG_INVALID", mensaje: "Perfil colombiano inconsistente." }); if (c.identidadFiscal.numeroDocumento !== undefined || c.identidadFiscal.digitoVerificacion !== undefined) if (c.identidadFiscal.tipoDocumento !== "NIT" || !nitValido(c.identidadFiscal.numeroDocumento ?? "", c.identidadFiscal.digitoVerificacion ?? "")) errores.push({ ruta: "identidadFiscal", codigo: "CONFIG_INVALID", mensaje: "NIT o dígito de verificación inválido." }); if (c.identidadFiscal.regimenTributario !== undefined && !enumEn(c.identidadFiscal.regimenTributario, PERFIL_FISCAL_COLOMBIA.regimenesTributarios)) errores.push({ ruta: "identidadFiscal.regimenTributario", codigo: "CONFIG_INVALID", mensaje: "Régimen inválido." }); }
  if (!enumEn(c.impuestos?.impuestoTipoPredeterminado, ["excluido", "inc_8", "iva_19"]) || c.impuestos?.politicaRedondeo !== "POR_LINEA_ENTERA" || typeof c.impuestos?.preciosIncluyenImpuestos !== "boolean") errores.push({ ruta: "impuestos", codigo: "CONFIG_INVALID", mensaje: "Impuestos inválidos." });
  if (c.localizacion.paisFiscal === "CO") { const d = c.localizacion.direccion; if ((d.departamentoCodigo !== undefined && !/^\d{2}$/.test(d.departamentoCodigo)) || (d.municipioCodigo !== undefined && (!/^\d{5}$/.test(d.municipioCodigo) || (d.departamentoCodigo !== undefined && !d.municipioCodigo.startsWith(d.departamentoCodigo))))) errores.push({ ruta: "localizacion.direccion", codigo: "CONFIG_INVALID", mensaje: "Códigos territoriales colombianos inválidos." }); if (c.identidadFiscal.actividadEconomicaPrincipal !== undefined && !/^\d{4}$/.test(c.identidadFiscal.actividadEconomicaPrincipal)) errores.push({ ruta: "identidadFiscal.actividadEconomicaPrincipal", codigo: "CONFIG_INVALID", mensaje: "CIIU inválido." }); }
  errores.push(...validarBranding(c.branding).errores as ErrorBranding[]);
  const urlDocumentoSegura = (valor: unknown): boolean => { if (typeof valor !== "string") return false; try { const url = new URL(valor); return url.protocol === "https:" && !url.username && !url.password && !/(?:token|secret|signature|credential)=/i.test(url.search); } catch { return false; } };
  if (typeof c.ticket?.mensajePie !== "string" || !esTextoCanonico(c.ticket.mensajePie, 0, 300)) errores.push({ ruta: "ticket.mensajePie", codigo: "CONFIG_REQUIRED", mensaje: "Pie de ticket inválido." }); for (const k of ["mostrarLogoDocumento", "mostrarRazonSocial", "mostrarDireccion", "mostrarTelefono", "mostrarDesgloseImpuestos"] as const) if (typeof c.ticket?.[k] !== "boolean") errores.push({ ruta: `ticket.${k}`, codigo: "CONFIG_INVALID", mensaje: "Booleano inválido." }); if (c.ticket?.logoDocumentoUrl !== undefined && !urlDocumentoSegura(c.ticket.logoDocumentoUrl)) errores.push({ ruta: "ticket.logoDocumentoUrl", codigo: "CONFIG_INVALID", mensaje: "URL de logo inválida." }); if (c.ticket?.mostrarLogoDocumento && !c.ticket.logoDocumentoUrl) errores.push({ ruta: "ticket.mostrarLogoDocumento", codigo: "CONFIG_INVALID", mensaje: "Requiere logo de documento." });
  if (!enumEn(c.impresion?.formatoPapel, ["MM_58", "MM_80", "CARTA"]) || !entero(c.impresion?.copiasVenta, 1, 3) || !entero(c.impresion?.copiasCierre, 0, 3) || typeof c.impresion?.autoImprimirVenta !== "boolean" || typeof c.impresion?.autoAbrirCajon !== "boolean") errores.push({ ruta: "impresion", codigo: "CONFIG_INVALID", mensaje: "Impresión inválida." });
  lista(c.pos?.metodosPagoHabilitados, "pos.metodosPagoHabilitados", METODOS_PAGO_CONFIGURACION, errores); if (!enumEn(c.pos?.metodoPagoPredeterminado, METODOS_PAGO_CONFIGURACION) || !c.pos?.metodosPagoHabilitados?.includes(c.pos.metodoPagoPredeterminado) || c.pos.permitirPagoMixto !== c.pos.metodosPagoHabilitados?.includes("mixto")) errores.push({ ruta: "pos", codigo: "CONFIG_INVALID", mensaje: "Pagos inconsistentes." }); if (contexto.metodosPagoPermitidos && c.pos?.metodosPagoHabilitados?.some((x) => !contexto.metodosPagoPermitidos!.includes(x))) errores.push({ ruta: "pos.metodosPagoHabilitados", codigo: "CONFIG_INVALID", mensaje: "Método fuera del Plan." });
  if (!entero(c.caja?.baseAperturaSugerida, 0) || !entero(c.caja?.umbralAlertaFaltante, 0) || typeof c.caja?.permitirRelevo !== "boolean") errores.push({ ruta: "caja", codigo: "CONFIG_INVALID", mensaje: "Caja inválida." }); lista(c.caja?.rolesConTurnoObligatorio, "caja.rolesConTurnoObligatorio", ROLES_TURNO_CONFIGURACION, errores); lista(c.modulos?.habilitados, "modulos.habilitados", MODULOS_CONFIGURACION, errores); if (contexto.modulosPermitidos && c.modulos?.habilitados?.some((x) => !contexto.modulosPermitidos!.includes(x))) errores.push({ ruta: "modulos.habilitados", codigo: "CONFIG_INVALID", mensaje: "Módulo fuera del Plan." }); for (const modulo of c.modulos?.habilitados ?? []) if (DEPENDENCIAS_MODULOS_CONFIGURACION[modulo].some((d) => !c.modulos.habilitados.includes(d))) errores.push({ ruta: "modulos.habilitados", codigo: "CONFIG_INVALID", mensaje: "Dependencia de módulo ausente." });
  if (c.kds?.ordenComandas !== "ANTIGUEDAD_ASC" || !entero(c.kds?.minutosAlerta, 1, 240) || !entero(c.kds?.minutosCritico, 2, 480) || c.kds.minutosAlerta >= c.kds.minutosCritico || typeof c.kds.agruparPorPedido !== "boolean") errores.push({ ruta: "kds", codigo: "CONFIG_INVALID", mensaje: "KDS inválido." }); if (c.autenticacionOperativa?.metodoPrincipal !== "CODIGO_PIN" || !entero(c.autenticacionOperativa?.longitudPin, 4, 12) || !entero(c.autenticacionOperativa?.maxFallosConsecutivos, 1, 20) || !entero(c.autenticacionOperativa?.bloqueoMinutos, 1, 1440) || typeof c.autenticacionOperativa?.exigirCambioCredencialTemporal !== "boolean") errores.push({ ruta: "autenticacionOperativa", codigo: "CONFIG_INVALID", mensaje: "Autenticación inválida." }); if (!esTextoCanonico(c.preferencias?.formatoFecha) || !enumEn(c.preferencias?.formatoHora, ["H12", "H24"]) || !enumEn(c.preferencias?.primerDiaSemana, ["DOMINGO", "LUNES"]) || typeof c.preferencias?.mostrarCentavos !== "boolean") errores.push({ ruta: "preferencias", codigo: "CONFIG_INVALID", mensaje: "Preferencias inválidas." });
  if (!enumEn(c.ultimaMutacion?.actorTipo, ["USER", "SYSTEM", "PLATFORM"]) || !enumEn(c.ultimaMutacion?.origen, ["BOOTSTRAP", "BACKFILL", "ADMIN", "ONBOARDING", "PLATFORM", "RECOVERY"])) errores.push({ ruta: "ultimaMutacion", codigo: "CONFIG_INVALID", mensaje: "Metadatos de mutación inválidos." }); else ["actorId", "commandId", "correlationId"].forEach((k) => obligatorio((c.ultimaMutacion as unknown as Record<string, unknown>)[k], `ultimaMutacion.${k}`, errores));
  return { valida: errores.length === 0, errores, valor: errores.length === 0 ? c : undefined };
}

export function paisFiscalSoportado(pais: string): boolean { return (PAISES_FISCALES_SOPORTADOS as readonly string[]).includes(pais); }
