export const FACULTADES_PLATAFORMA = [
  "OPERADORES_GOBERNAR",
  "COMERCIAL_GOBERNAR",
  "BOOTSTRAP_EMPRESARIAL_SOLICITAR",
  "LIFECYCLE_GOBERNAR",
  "CONSERVACION_GOBERNAR",
  "PLATAFORMA_CONSULTAR",
  "ACCESO_RESTABLECER",
  "DUSEMA_TENANT_CONSULTAR",
] as const;

export type FacultadPlataforma = (typeof FACULTADES_PLATAFORMA)[number];

/** Las facultades nuevas requieren asignación explícita tras el bootstrap inicial. */
export const FACULTADES_BOOTSTRAP_POR_DEFECTO = [
  "OPERADORES_GOBERNAR",
  "COMERCIAL_GOBERNAR",
  "BOOTSTRAP_EMPRESARIAL_SOLICITAR",
  "LIFECYCLE_GOBERNAR",
  "CONSERVACION_GOBERNAR",
  "PLATAFORMA_CONSULTAR",
  "ACCESO_RESTABLECER",
] as const satisfies readonly FacultadPlataforma[];
export type EstadoOperador = "ACTIVO" | "SUSPENDIDO" | "REVOCADO";

export interface OperadorSaas {
  schemaVersion: 1;
  uid: string;
  estado: EstadoOperador;
  facultades: FacultadPlataforma[];
  versionAutorizacion: number;
  creadoEn: unknown;
  actualizadoEn: unknown;
  creadoPor: { tipo: "BOOTSTRAP" | "OPERADOR"; uid: string | null };
  ultimoCambioPorUid: string;
  motivoCambioCodigo: string;
}

export interface ClaimsSaas {
  operador: boolean;
  versionAutorizacion: number;
  facultades: FacultadPlataforma[];
}

export interface EnvelopePlataforma {
  commandId: string;
  idempotencyKey: string;
  correlationId: string;
  causationId: string | null;
  motivoCodigo: string;
}

export type ResultadoAuditoria =
  | "CONFIRMADO"
  | "DENEGADO"
  | "CONFLICTO"
  | "FALLO_RECUPERABLE";

export type TipoAuditoria =
  | "OPERADOR_INCORPORADO"
  | "OPERADOR_FACULTADES_CAMBIADAS"
  | "OPERADOR_SUSPENDIDO"
  | "OPERADOR_REACTIVADO"
  | "OPERADOR_REVOCADO"
  | "PLAN_CREADO"
  | "PLAN_VERSION_CREADA"
  | "PLAN_BORRADOR_ACTUALIZADO"
  | "PLAN_VERSION_PUBLICADA"
  | "PLAN_VERSION_RETIRADA"
  | "SUSCRIPCION_CREADA"
  | "SUSCRIPCION_RELACION_CONTRACTUAL_CREADA"
  | "SUSCRIPCION_ACTIVADA"
  | "SUSCRIPCION_RENOVADA"
  | "SUSCRIPCION_PLAN_CAMBIADO"
  | "SUSCRIPCION_MORA_MARCADA"
  | "SUSCRIPCION_SUSPENDIDA"
  | "SUSCRIPCION_CANCELACION_PROGRAMADA"
  | "SUSCRIPCION_CANCELACION_REVOCADA"
  | "SUSCRIPCION_CANCELADA"
  | "SUSCRIPCION_REACTIVADA"
  | "SUSCRIPCION_PAGO_ANUAL_CONFIRMADO"
  | "SUSCRIPCION_RELACION_PAGO_ANUAL_CONFIRMADO"
  | "SUSCRIPCION_RELACION_TRIAL_VENCIDO"
  | "SUSCRIPCION_RELACION_PERIODO_ANUAL_VENCIDO"
  | "SUSCRIPCION_TRIAL_VENCIDO"
  | "SUSCRIPCION_PERIODO_ANUAL_VENCIDO"
  | "BOOTSTRAP_EMPRESARIAL_SOLICITADO"
  | "BOOTSTRAP_EMPRESARIAL_COMPLETADO"
  | "EMPRESA_ACTIVADA"
  | "EMPRESA_SUSPENDIDA"
  | "EMPRESA_CANCELADA"
  | "EMPRESA_REACTIVADA"
  | "EMPRESA_ARCHIVADA"
  | "EMPRESA_RESTAURADA"
  | "EMPRESA_ELIMINADA"
  | "EMPRESA_DATOS_ADMINISTRATIVOS_ACTUALIZADOS"
  | "CREDENCIAL_INICIAL_EMITIDA"
  | "CREDENCIAL_INICIAL_REEMITIDA"
  | "CREDENCIAL_INICIAL_ACTIVADA"
  | "CREDENCIAL_INICIAL_DESBLOQUEADA"
  | "CREDENCIAL_RESTABLECIMIENTO_SOLICITADO"
  | "CREDENCIAL_RESTABLECIMIENTO_ACTIVADO"
  | "CREDENCIAL_RESTABLECIMIENTO_CANCELADO"
  | "EXPORTACION_SOLICITADA"
  | "EXPORTACION_COMPLETADA"
  | "EXPORTACION_RECHAZADA"
  | "EXPORTACION_FALLIDA"
  | "AUTORIZACION_DENEGADA"
  | "FACULTAD_AUSENTE"
  | "OPERADOR_INACTIVO"
  | "AUTOESCALAMIENTO_DENEGADO"
  | "ALCANCE_DENEGADO"
  | "CONTEXTO_PLATAFORMA_OBSOLETO"
  | "CONFLICTO_IDEMPOTENCIA"
  | "CONFLICTO_REVISION"
  | "SOPORTE_SOLICITADO"
  | "SOPORTE_RECHAZADO"
  | "SOPORTE_AUTORIZADO"
  | "SOPORTE_REVOCADO"
  | "SOPORTE_EXPIRADO"
  | "SOPORTE_INICIADO"
  | "SOPORTE_FINALIZADO"
  | "SOPORTE_ALCANCE_RECHAZADO"
  | "SOPORTE_ACCESO_FUERA_DE_ALCANCE_DENEGADO"
  | "SOPORTE_DIAGNOSTICO_ALTO_RIESGO";

export type TipoAgregadoAuditoria =
  | "OPERADOR"
  | "PLAN"
  | "SUSCRIPCION"
  | "EMPRESA"
  | "PROVISIONAMIENTO_EMPRESARIAL"
  | "CONSERVACION"
  | "RECUPERACION_CREDENCIAL"
  | "SOPORTE_AUTORIZACION"
  | "SOPORTE_SESION"
  | "SEGURIDAD_PLATAFORMA";

export function esFacultadPlataforma(value: unknown): value is FacultadPlataforma {
  return typeof value === "string"
    && (FACULTADES_PLATAFORMA as readonly string[]).includes(value);
}

export function facultadesValidas(value: unknown): value is FacultadPlataforma[] {
  return Array.isArray(value)
    && value.length > 0
    && value.every(esFacultadPlataforma)
    && new Set(value).size === value.length;
}

