import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { exigirTenantActivo } from "../operational-auth";
import { crearIdentificadorInterno } from "../turnos/identificadores";
import { crearHuellaSemantica, revalidarAutoridadFinancieraEnTransaccion } from "./callables";

const REGION = "us-central1";
const MOVIMIENTOS = "transacciones_financieras";
type Tipo = "ingreso" | "egreso";
interface Envelope { commandId: string; idempotencyKey: string; correlationId: string; causationId?: string | null; motivo?: string | null; payload: Record<string, unknown>; }
export interface ContextoFinancieroOperativo { empresaId: string; actorUid: string; rol: string; }

const fail = (code: HttpsError["code"], dominio: string): never => { throw new HttpsError(code, "No fue posible completar la anulación de la venta.", { code: dominio }); };
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const text = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;
const money = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value > 0;
function envelope(value: unknown): Envelope { if (!object(value) || !text(value.commandId) || !text(value.idempotencyKey) || !text(value.correlationId) || !object(value.payload)) fail("invalid-argument", "PAYLOAD_INVALID"); return value as Envelope; }
function refs(db: any, empresaId: string, input: Envelope) { return { recibo: db.collection("operaciones_comandos").doc(crearIdentificadorInterno(empresaId, input.commandId)), indice: db.collection("operaciones_command_idempotency").doc(crearIdentificadorInterno(empresaId, input.idempotencyKey)), auditoria: db.collection("operaciones_auditoria").doc(crearIdentificadorInterno(empresaId, input.commandId)) }; }
async function account(tx: any, db: any, empresaId: string, id: string) { const ref = db.collection("cuentas_bancarias").doc(id); const snap = await tx.get(ref); if (!snap.exists || snap.data()?.empresaId !== empresaId) fail("failed-precondition", "CUENTA_INVALIDA"); const saldo = snap.data()?.saldo; if (!Number.isSafeInteger(saldo) || saldo < 0) fail("failed-precondition", "CUENTA_INVALIDA"); return { ref, data: snap.data() as Record<string, unknown>, saldo: saldo as number }; }
async function turnoAbierto(tx: any, db: any, empresaId: string, turnoId: unknown) { if (!text(turnoId)) fail("failed-precondition", "TURNO_CERRADO"); const snap = await tx.get(db.collection("turnos").doc(turnoId)); if (!snap.exists || snap.data()?.empresaId !== empresaId || snap.data()?.estado !== "abierto") fail("failed-precondition", "TURNO_CERRADO"); }
function replay(recibo: any, indice: any, empresaId: string, input: Envelope, huella: string, reciboPath: string): unknown | null { if (!recibo.exists && !indice.exists) return null; const r = recibo.data(); const i = indice.data(); if (!recibo.exists || !r || r.empresaId !== empresaId || r.commandId !== input.commandId || r.idempotencyKey !== input.idempotencyKey || r.huella !== huella) fail("already-exists", "COMMAND_ID_CONFLICT"); if (!indice.exists || !i || i.empresaId !== empresaId || i.commandId !== input.commandId || i.idempotencyKey !== input.idempotencyKey || i.huella !== huella || i.reciboPath !== reciboPath) fail("already-exists", "IDEMPOTENCY_CONFLICT"); return r.resultado ?? fail("already-exists", "COMMAND_ID_CONFLICT"); }
function confirm(tx: any, r: ReturnType<typeof refs>, empresaId: string, actorUid: string, rol: string, input: Envelope, huella: string, result: Record<string, unknown>) { const now = FieldValue.serverTimestamp(); const actor = { uid: actorUid, rolEfectivo: rol }; const causationId = input.causationId ?? null; tx.create(r.recibo, { empresaId, commandId: input.commandId, idempotencyKey: input.idempotencyKey, huella, tipo: "anularVentaOperativaV1", actor, correlationId: input.correlationId, causationId, motivo: input.motivo ?? null, resultado: result, referencias: result, estado: "CONFIRMADO", creadoEn: now }); tx.create(r.indice, { empresaId, commandId: input.commandId, idempotencyKey: input.idempotencyKey, huella, reciboPath: r.recibo.path, creadoEn: now }); tx.create(r.auditoria, { empresaId, tipo: "anularVentaOperativaV1", resultado: "CONFIRMADO", actor, correlationId: input.correlationId, causationId, comando: { id: input.commandId, tipo: "anularVentaOperativaV1", idempotencyKey: input.idempotencyKey, huella, correlationId: input.correlationId, causationId }, motivo: input.motivo ?? null, referencias: result, creadoEn: now }); }
function movement(tx: any, db: any, input: { empresaId: string; command: Envelope; key: string; cuenta: { ref: any; data: Record<string, unknown>; saldo: number }; monto: number; actorUid: string; rol: string; turnoId: string | null; ventaId: string; relacionado: string }) { const id = crearIdentificadorInterno(input.empresaId, `movfin:${input.key}`); const next = input.cuenta.saldo - input.monto; if (next < 0) fail("failed-precondition", "FONDOS_INSUFICIENTES"); tx.create(db.collection(MOVIMIENTOS).doc(id), { id, empresaId: input.empresaId, claveIdempotencia: input.key, commandId: input.command.commandId, idempotencyKey: input.command.idempotencyKey, correlationId: input.command.correlationId, causationId: input.command.causationId ?? null, tipo: "egreso" as Tipo, monto: input.monto, moneda: "COP", fecha: FieldValue.serverTimestamp(), cuentaDocumentoId: input.cuenta.ref.id, cuentaClaveSnapshot: input.cuenta.data.claveOperativa ?? input.cuenta.ref.id, cuentaNombreSnapshot: input.cuenta.data.nombre ?? input.cuenta.ref.id, saldoDespues: next, categoria: "anulacion_venta", referenciaColeccion: "ventas", referenciaId: input.ventaId, turnoId: input.turnoId, ventaId: input.ventaId, egresoId: null, movimientoRelacionadoId: input.relacionado, motivo: input.command.motivo ?? null, usuarioId: input.actorUid, usuarioNombreSnapshot: input.actorUid, rolEfectivoSnapshot: input.rol }); return { id, saldo: next }; }

export function importesPagoVenta(venta: Record<string, any>): number[] | null { const total = Number(venta.totales?.total ?? 0); const metodo = venta.metodoPago ?? venta.pago?.metodo; if (!money(total) || !text(metodo)) return null; if (metodo !== "mixto") return [total]; if (!Array.isArray(venta.pagoMixtoDetalle) || venta.pagoMixtoDetalle.length === 0) return null; const importes = venta.pagoMixtoDetalle.map((p: any) => p?.monto); return importes.every(money) && importes.reduce((sum: number, monto: number) => sum + monto, 0) === total ? importes : null; }

export async function ejecutarAnularVentaOperativaV1(db: any, contexto: ContextoFinancieroOperativo, data: unknown) {
  const input = envelope(data); const huella = crearHuellaSemantica({ tipo: "anularVentaOperativaV1", causationId: input.causationId ?? null, motivo: input.motivo ?? null, payload: input.payload }); const operation = refs(db, contexto.empresaId, input);
  return db.runTransaction(async (tx: any) => {
    const existing = replay(...await Promise.all([tx.get(operation.recibo), tx.get(operation.indice)]), contexto.empresaId, input, huella, operation.recibo.path); if (existing) return existing;
    await revalidarAutoridadFinancieraEnTransaccion(tx, db, contexto, "pos");
    const ventaIdEntrada = input.payload.ventaId; const ventaId = text(ventaIdEntrada) ? ventaIdEntrada : fail("invalid-argument", "PAYLOAD_INVALID"); if (contexto.rol !== "admin" && contexto.rol !== "cajero") fail("permission-denied", "ROL_NO_AUTORIZADO");
    const ventaRef = db.collection("ventas").doc(ventaId); const venta = await tx.get(ventaRef); if (!venta.exists || venta.data()?.empresaId !== contexto.empresaId) fail("not-found", "VENTA_NO_ENCONTRADA"); const ventaData = venta.data() as Record<string, any>; const estado = ventaData.estadoOperativo;
    if (estado === "ANULADA_SIN_EFECTOS" || estado === "ANULADA_CON_EFECTOS" || ventaData.estado === "anulada") fail("failed-precondition", "VENTA_YA_ANULADA");
    if (estado === "PENDIENTE_EFECTOS") { tx.update(ventaRef, { estado: "anulada", estadoOperativo: "ANULADA_SIN_EFECTOS", anuladaPor: contexto.actorUid, anuladaPorNombre: contexto.actorUid, anuladaEn: FieldValue.serverTimestamp() }); const result = { commandId: input.commandId, ventaId, estadoOperativo: "ANULADA_SIN_EFECTOS", movimientos: [] }; confirm(tx, operation, contexto.empresaId, contexto.actorUid, contexto.rol, input, huella, result); return result; }
    if (estado !== "COMPLETO") fail("failed-precondition", "ESTADO_VENTA_INVALIDO"); const importes = importesPagoVenta(ventaData) ?? fail("failed-precondition", "PAGO_INVALIDO");
    const fuentes = await Promise.all(importes.map((monto, ordinal) => tx.get(db.collection(MOVIMIENTOS).doc(crearIdentificadorInterno(contexto.empresaId, `movfin:venta:${ventaId}:pago:${ordinal}`))).then((snap: any) => ({ snap, monto, ordinal }))));
    if (fuentes.some(({ snap, monto }) => !snap.exists || snap.data()?.empresaId !== contexto.empresaId || snap.data()?.ventaId !== ventaId || snap.data()?.tipo !== "ingreso" || snap.data()?.categoria !== "ventas" || snap.data()?.monto !== monto || !text(snap.data()?.cuentaDocumentoId))) fail("failed-precondition", "EFECTOS_VENTA_INCONSISTENTES");
    const cuentas = await Promise.all([...new Set(fuentes.map(({ snap }) => snap.data().cuentaDocumentoId as string))].map(id => account(tx, db, contexto.empresaId, id))); const porId = new Map(cuentas.map(cuenta => [cuenta.ref.id, cuenta])); const debitos = new Map<string, number>(); for (const { snap, monto } of fuentes) { const id = snap.data().cuentaDocumentoId as string; debitos.set(id, (debitos.get(id) ?? 0) + monto); } for (const [id, monto] of debitos) if ((porId.get(id)?.saldo ?? -1) < monto) fail("failed-precondition", "FONDOS_INSUFICIENTES");
    const efectivo = fuentes.some(({ snap }) => snap.data()?.cuentaClaveSnapshot === "caja-principal" || snap.data()?.cuentaDocumentoId === "caja-principal"); let turnoId: string | null = null; if (efectivo) { const lock = await tx.get(db.collection("turnos_activos").doc(crearIdentificadorInterno(contexto.empresaId, contexto.actorUid))); const turnoActual = lock.data()?.turnoId; if (!lock.exists || lock.data()?.empresaId !== contexto.empresaId || lock.data()?.cajeroId !== contexto.actorUid || !text(turnoActual)) fail("failed-precondition", "TURNO_CERRADO"); await turnoAbierto(tx, db, contexto.empresaId, turnoActual); turnoId = turnoActual; }
    const saldos = new Map(cuentas.map(cuenta => [cuenta.ref.id, cuenta.saldo])); const movimientos: string[] = []; for (const { snap, monto, ordinal } of fuentes) { const cuentaId = snap.data().cuentaDocumentoId as string; const cuenta = porId.get(cuentaId)!; const esEfectivo = snap.data()?.cuentaClaveSnapshot === "caja-principal" || cuentaId === "caja-principal"; const item = movement(tx, db, { empresaId: contexto.empresaId, command: input, key: `anulacion:${ventaId}:pago:${ordinal}`, cuenta: { ...cuenta, saldo: saldos.get(cuentaId)! }, monto, actorUid: contexto.actorUid, rol: contexto.rol, turnoId: esEfectivo ? turnoId : null, ventaId, relacionado: snap.id }); saldos.set(cuentaId, item.saldo); movimientos.push(item.id); }
    for (const cuenta of cuentas) tx.update(cuenta.ref, { saldo: saldos.get(cuenta.ref.id)! }); tx.update(ventaRef, { estado: "anulada", estadoOperativo: "ANULADA_CON_EFECTOS", anuladaPor: contexto.actorUid, anuladaPorNombre: contexto.actorUid, anuladaEn: FieldValue.serverTimestamp() }); const result = { commandId: input.commandId, ventaId, estadoOperativo: "ANULADA_CON_EFECTOS", movimientos, turnoCompensacion: turnoId }; confirm(tx, operation, contexto.empresaId, contexto.actorUid, contexto.rol, input, huella, result); return result;
  });
}
export async function manejarAnularVentaOperativaV1(db: any, request: any) { const tenant = await exigirTenantActivo(request, db); return ejecutarAnularVentaOperativaV1(db, { empresaId: tenant.id, actorUid: request.auth.uid, rol: tenant.rol }, request.data); }
export const anularVentaOperativaV1 = onCall({ region: REGION }, async request => manejarAnularVentaOperativaV1(getFirestore(), request));
