import assert from 'node:assert/strict'
import test from 'node:test'
import { crearPlantillaConfiguracionRevision1 } from '../plantilla'
import { resolverBrandingRuntime } from '../branding-runtime'
const base = () => crearPlantillaConfiguracionRevision1({ empresaId: 'e1', nombreComercial: 'Neutral', creadaEn: {}, actualizadaEn: {}, ultimaMutacion: { actorTipo: 'SYSTEM', actorId: 'system', origen: 'BOOTSTRAP', commandId: 'c', correlationId: 'x' } })
test('B1.7 usa tema SaaS neutral sin tenant y resuelve Branding parcial sobre la base neutral', () => { assert.equal(resolverBrandingRuntime(null).valido, false); assert.equal(resolverBrandingRuntime(base()).nombreVisible, 'Neutral') })
test('B1.7 resuelve tokens y los tres modos visuales', () => { for (const modoVisual of ['LIGHT', 'DARK', 'SYSTEM'] as const) { const c = base(); c.branding = { ...c.branding, nombreVisible: 'Empresa Uno', modoVisual, paletas: { light: { primary: '#000000', onPrimary: '#FFFFFF' }, dark: { primary: '#FFFFFF', onPrimary: '#000000' } } }; const r = resolverBrandingRuntime(c); assert.equal(r.valido, true); assert.equal(r.modo, modoVisual); assert.equal(r.variablesLight['--primary'], '#000000') } })
test('B1.7 rechaza Branding inválido y aplica exclusivamente el tema neutral', () => { const c = base(); c.branding = { ...c.branding, nombreVisible: 'Empresa', paletas: { light: { primary: '#FFFFFF', onPrimary: '#FFFFFE' }, dark: { primary: '#FFFFFF', onPrimary: '#000000' } } }; const r = resolverBrandingRuntime(c); assert.equal(r.valido, false); assert.equal(r.variablesLight['--primary'], '#334155') })
test('B1.7 rechaza modos visuales fuera del catálogo', () => { const c = base(); c.branding.modoVisual = 'BLUE' as never; assert.equal(resolverBrandingRuntime(c).valido, false) })
test('B1.7 resuelve logos versionados para modo claro y oscuro', () => { const c = base(); c.branding = { ...c.branding, nombreVisible: 'Empresa Uno', assets: { logoPrincipal: { ubicacion: 'https://assets.example/logo.png', versionContenido: 'v1', tipo: 'image/png' }, logoModoOscuro: { ubicacion: 'https://assets.example/logo-dark.png', versionContenido: 'v2', tipo: 'image/png' } }, paletas: { light: { primary: '#000000', onPrimary: '#FFFFFF' }, dark: { primary: '#FFFFFF', onPrimary: '#000000' } } }; const r = resolverBrandingRuntime(c); assert.equal(r.logo, 'https://assets.example/logo.png'); assert.equal(r.logoOscuro, 'https://assets.example/logo-dark.png') })
